// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVWVeEd3vxiV7kK7gvz4PL9K6tbESN0Hs',
    appId: '1:1051313185256:web:b6e639ef4d4cc91327445d',
    messagingSenderId: '1051313185256',
    projectId: 'todo-app-8793a',
    authDomain: 'todo-app-8793a.firebaseapp.com',
    storageBucket: 'todo-app-8793a.appspot.com',
    measurementId: 'G-FC24WE6SP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQOPEHZaw1wJpPiAQ1tnVrmxKT2DYFwOU',
    appId: '1:1051313185256:android:0e72d8ff9891aeab27445d',
    messagingSenderId: '1051313185256',
    projectId: 'todo-app-8793a',
    storageBucket: 'todo-app-8793a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7oVNKqMAo8mRX6mYwCf_f-TPPxnOJhf0',
    appId: '1:1051313185256:ios:86f9dbcca1ee439827445d',
    messagingSenderId: '1051313185256',
    projectId: 'todo-app-8793a',
    storageBucket: 'todo-app-8793a.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7oVNKqMAo8mRX6mYwCf_f-TPPxnOJhf0',
    appId: '1:1051313185256:ios:b59fef90d7b1092727445d',
    messagingSenderId: '1051313185256',
    projectId: 'todo-app-8793a',
    storageBucket: 'todo-app-8793a.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
